### ISSUE TITLE
Alexa Skills Kit video no longer working

### ISSUE THREAD

**Issue by karthikeayan** [alexa/skill-sample-nodejs-howto#10]
I am trying to open the video link from this line, but it says "This presentation is no longer available."

Use JavaScript/Node.js and the Alexa Skills Kit to create a skill - You will use the template as a guide but the customization is up to you. For more background information on using the Alexa Skills Kit please watch this video.

**Comment by JennJin** [comment]
@akersh-s Can you update the link to the video in the README.md?

**Comment by franklin-lobb** [comment]
The link to the video has been removed.
