### ISSUE TITLE
Card Title and Content out of wack

### ISSUE THREAD

**Issue by pettittmj** [alexa/skill-sample-nodejs-howto#14]
When testing the card response,  the Title and Content are not returned correctly.  I even ran this with the default app and configurations not changing anything and it is not returning the correct values for these.

thanks

**Comment by pettittmj** [comment]
May be an issue with this like being changed from:
 this.emit(':askWithCard', recipe, this.attributes['repromptSpeech'], cardTitle, recipe);

to

 this.emit(':tellWithCard', recipe, this.attributes['repromptSpeech'], cardTitle, recipe);

I'm not very experienced so I would like a second opinion.

**Comment by Veiam** [comment]
Good suggestion, but it still does not work.
Did anyone figure this out?

**Comment by jaydjohno** [comment]
Hiya, i only just seen this as i was looking for help.

I was able to figure out where the json request was coming from thanks to veiam's help.

I have managed to fix it with this.

if (recipe) {
            this.attributes['speechOutput'] = recipe;
            this.attributes['repromptSpeech'] = this.t("RECIPE_REPEAT_MESSAGE");
            this.emit(':tellWithCard', recipe, cardTitle, recipe);

There is too many functions added to the code, remove the reprompt speech option and this fixes the card :)
