### ISSUE TITLE
Entity resolution

### ISSUE THREAD

**Issue by dstepp** [alexa/skill-sample-nodejs-howto#21]
I have the original skill working, but am having trouble getting the newer entity resolution feature added using synonyms. It would be great if you could update the documentation to explain how to use this feature.

**Comment by franklin-lobb** [comment]
Thanks for the suggestion.  We'll evaluate incorporating entity resolution / synonyms into the sample.  In the meantime, here are a couple of examples using entity resolution:
https://github.com/alexa/skill-sample-nodejs-petmatch
https://github.com/alexa/skill-sample-nodejs-the-foodie
https://github.com/alexa/alexa-cookbook/tree/master/feature-demos/skill-demo-entity-resolution
