### ISSUE TITLE
Bad AWS nodejs instructions in documentation

### ISSUE THREAD

**Issue by jjbenjohn** [alexa/skill-sample-nodejs-howto#22]
In step #5 of "Setting up a Lambda Function," the documentation dealing with the downloaded code says:

On your local machine, go to the 'skill-sample-nodejs-howto/lambda/' directory and run 'deploy.js' using Node.
        npm install aws-sdk
        node deploy.js

An error is thrown because there is no 'deploy.js' file to be found.

-------------------------------------------------------------------------------------------
jbj@MININT-MTSHK4F MINGW64 ~/Desktop/skill-sample-nodejs-howto-master/lambda
$ dir
custom  node_modules

jbj@MININT-MTSHK4F MINGW64 ~/Desktop/skill-sample-nodejs-howto-master/lambda
$ dir custom
index.js  package.json  recipes.js

jbj@MININT-MTSHK4F MINGW64 ~/Desktop/skill-sample-nodejs-howto-master/lambda
$ node deploy.js
module.js:472
    throw err;
    ^

Error: Cannot find module 'C:\Users\John\Desktop\skill-sample-nodejs-howto-maste
r\lambda\deploy.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3

jbj@MININT-MTSHK4F MINGW64 ~/Desktop/skill-sample-nodejs-howto-master/lambda
-------------------------------------------------------------------------------------------

**Comment by smach** [comment]
Same issue. I don't see any deploy.js file in the GitHub repo. Is that file needed for the skill to work? Or are the instructions outdated? Can someone please respond? Thank you.

**Comment by kahlil29** [comment]
Same issue. Wtf is the support or maintainers of the repo?

**Comment by mcarvalho21** [comment]
I'm having the same issue. I'm trying to figure out.

**Comment by GeoffState** [comment]
**mcarvalho21** you are a saint! **JakeMKelly where are you?**

**Comment by franklin-lobb** [comment]
this looks to have been sorted out previously, and does not apply to the current version of the skill/tutorial.  Closing...
