### ISSUE TITLE
Your model used a depreciated format

### ISSUE THREAD

**Issue by GeoffState** [alexa/skill-sample-nodejs-howto#25]
Messages from ALEXA SKILLS KIT | SKILL BUILDER BETA on developer.amazon.com
Your interaction model did not validate. Check below for errors.
Your model used a depreciated format...

**Comment by JennJin** [comment]
What part of the Interaction Model had errors? The validator should highlight the errors.
The 2nd message, "Your model used a depreciated format..." is informational, to let you know the format has been updated.

**Comment by franklin-lobb** [comment]
The model has been updated in the sample.  Closing...
