### ISSUE TITLE
Way to close session after question answered

### ISSUE THREAD

**Issue by alex-sanders** [alexa/skill-sample-nodejs-howto#29]
Hello! 

Trying to end a session after a question is asked. Would the easiest way be to use the SessionEndedReuest? 

Thank you!

```
        if (recipe) {
            this.attributes.speechOutput = recipe;
            this.attributes.repromptSpeech = this.t('RECIPE_REPEAT_MESSAGE');
            this.emit(':askWithCard', recipe, this.attributes.repromptSpeech, cardTitle, recipe);
            **this.emit('SessionEndedRequest');**
        }
```

**SessionEndedRequest (from later in .js):**
```
    'SessionEndedRequest': function () {
        this.emit(':tell', this.t('STOP_MESSAGE'));
    },
```

**Comment by franklin-lobb** [comment]
If you are using the v1 ASK SDK for Node.js (which includes the user of ":askWithCard", then change the ":askWithCard" to ":tellWithCard" to close the session after Alexa speaks. 

I'd recommend migrating to the newer version of the ASK SDK for Node.js if you can.
