### ISSUE TITLE
Use slots with capital letters

### ISSUE THREAD

**Issue by caffeinePlease** [alexa/skill-sample-nodejs-howto#46]
As it stands, the slot values in recipes.js are all lower case. In my custom version of the skill, I've changed them all to capitalized and changed the corresponding values in the interaction model to be the same thing.

Yet, the skill will not function unless they're both completely lowercase. I plan on adding images to make better use of cards/devices with a screen but the titles aren't pleasantly formatted, since the recipes show up lowercase. How can I fix this?

**Comment by franklin-lobb** [comment]
with the way the data for the recipes is structured, there might not be a way to do this.  The values passed by Alexa from the speech recognition are normally in lowercase.  If you didn't want to restructure the recipe data, you could create a second data structure with the display formatted values, however that seems like it would be cumbersome to manage.  It might be possible to leverage the value's id field in the interaction model.

**Comment by franklin-lobb** [comment]
I looked into this a little bit more.  You can use formatted case if you do the following:
1. Update the slot type's value to be the value as desired (e.g. Snow Golem)
2. Update the value in the recipe.js file to match that value.
3. Replace line 44 (`itemName = itemSlot.value.toLowerCase();`) with this code:
```
      if (itemSlot.resolutions.resolutionsPerAuthority[0].status.code === 'ER_SUCCESS_MATCH') {
        itemName = itemSlot.resolutions.resolutionsPerAuthority[0].values[0].value.name;
      } else {
        itemName = itemSlot.value.toLowerCase();
      }
```
The item slot's value will always be converted to lower case, so to get the formatted value you have to pull it from the resolved match, which will only be present if there was a match.
