### ISSUE TITLE
lambda function for howto returns error on invocation

### ISSUE THREAD

**Issue by justindeardorff** [alexa/skill-sample-nodejs-howto#48]
When following the setup/install instructions as is, the lambda function created returns an error on invocation.

When I instead choose to use the Blueprint setup option with [alexa-skill-kit-sdk-howtoskill] as the blueprint template, the function works properly.

**Comment by franklin-lobb** [comment]
will investigate

**Comment by franklin-lobb** [comment]
could not reproduce with current instructions and SAR app.  Closing...
