### ISSUE TITLE
Recipe.js does not seem to be accessed

### ISSUE THREAD

**Issue by AlexaforMuggles** [alexa/skill-sample-nodejs-howto#49]
Two months ago the skill worked perfectly. Now when I test it, the skill will open and give the expected introduction but Alexa doesn't know any of the information that is in the recipe.js 

Here is the testing output: 
Testing output

{
	"version": "1.0",
	"session": {
		"new": false,
		"sessionId": "amzn1.echo-api.session.9972b07e-4016-4492-aa68-b80a98f547ce",
		"application": {
			"applicationId": "amzn1.ask.skill.aa3a79c1-f3ec-433c-a4a2-e41e6a325d5d"
		},
		"user": {
			"userId": "amzn1.ask.account.AHF34PRT27A6IOM3UWG3KZE3SN5MEMPSJTV7JS2T3B6CJ2MHZMSOBQT2Y2PQKG5QMLBNLF2XN7FTKZP57ZVTHCMT35Y5P3LMQDUAUMK5XWVKHD2VESU4PWTKGDCXR33BMXTU57JTATREXYUIXJWLRQY3BLJR6KBKIIN6CXOQKZ77KMAQH3XVFDQBHIULNGOD4ZZNEAKJW6US73Q"
		}
	},
	"context": {
		"AudioPlayer": {
			"playerActivity": "IDLE"
		},
		"Display": {
			"token": ""
		},
		"System": {
			"application": {
				"applicationId": "amzn1.ask.skill.aa3a79c1-f3ec-433c-a4a2-e41e6a325d5d"
			},
			"user": {
				"userId": "amzn1.ask.account.AHF34PRT27A6IOM3UWG3KZE3SN5MEMPSJTV7JS2T3B6CJ2MHZMSOBQT2Y2PQKG5QMLBNLF2XN7FTKZP57ZVTHCMT35Y5P3LMQDUAUMK5XWVKHD2VESU4PWTKGDCXR33BMXTU57JTATREXYUIXJWLRQY3BLJR6KBKIIN6CXOQKZ77KMAQH3XVFDQBHIULNGOD4ZZNEAKJW6US73Q"
			},
			"device": {
				"deviceId": "amzn1.ask.device.AG3ZSIVG4ANTEP42N6Q2ILIOFIU5UY574PHISS57PSBC2WXZCHTXBRCG73AQLMK53MSV6G5DLTTP4EC2ICKQZX4LDKT4BIQYBHRY5PMJ6BP7ZOSSWVTTIXM635OKPHE4RNCFGOBWOKD6YVKW2GKDEYAZ6D2Q",
				"supportedInterfaces": {
					"AudioPlayer": {},
					"Display": {
						"templateVersion": "1.0",
						"markupVersion": "1.0"
					}
				}
			},
			"apiEndpoint": "https://api.amazonalexa.com",
			"apiAccessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJhdWQiOiJodHRwczovL2FwaS5hbWF6b25hbGV4YS5jb20iLCJpc3MiOiJBbGV4YVNraWxsS2l0Iiwic3ViIjoiYW16bjEuYXNrLnNraWxsLmFhM2E3OWMxLWYzZWMtNDMzYy1hNGEyLWU0MWU2YTMyNWQ1ZCIsImV4cCI6MTUyNDgwNzYwOCwiaWF0IjoxNTI0ODA0MDA4LCJuYmYiOjE1MjQ4MDQwMDgsInByaXZhdGVDbGFpbXMiOnsiY29uc2VudFRva2VuIjpudWxsLCJkZXZpY2VJZCI6ImFtem4xLmFzay5kZXZpY2UuQUczWlNJVkc0QU5URVA0Mk42UTJJTElPRklVNVVZNTc0UEhJU1M1N1BTQkMyV1haQ0hUWEJSQ0c3M0FRTE1LNTNNU1Y2RzVETFRUUDRFQzJJQ0tRWlg0TERLVDRCSVFZQkhSWTVQTUo2QlA3Wk9TU1dWVFRJWE02MzVPS1BIRTRSTkNGR09CV09LRDZZVktXMkdLREVZQVo2RDJRIiwidXNlcklkIjoiYW16bjEuYXNrLmFjY291bnQuQUhGMzRQUlQyN0E2SU9NM1VXRzNLWkUzU041TUVNUFNKVFY3SlMyVDNCNkNKMk1IWk1TT0JRVDJZMlBRS0c1UU1MQk5MRjJYTjdGVEtaUDU3WlZUSENNVDM1WTVQM0xNUURVQVVNSzVYV1ZLSEQyVkVTVTRQV1RLR0RDWFIzM0JNWFRVNTdKVEFUUkVYWVVJWEpXTFJRWTNCTEpSNktCS0lJTjZDWE9RS1o3N0tNQVFIM1hWRkRRQkhJVUxOR09ENFpaTkVBS0pXNlVTNzNRIn19.Q9HAKaHUKV7mTzPIHiiyS-Bu3pdoFvhfVs9TlJCxxhKUNdbk-9feR9XfJ5Oda-rZO64kXo-FgRYXZpSwWdgbJXNvbWKeG2bUSPGPdcHAmRlb-Fhnqmli5KBvdl4D-3E9W9qvRH8_cEHRqDBvordKbxSBahXcqS91npsMRD7pzJoSFajZ6GrZsugNSD5AhTdjIyczmJ1NeOU_yMRwNprTrZ2AVQyCBpXesHasj5E9UaqIXh7c68X81budNatMfN4TraecM-iVcse8wg5OF9TfDmBr-tDeh4Wr9zFOfatrJSeZdY6k4vsdQsLjmgB2ngdogktH54YNgr3xHnPSZIqR7A"
		}
	},
	"request": {
		"type": "IntentRequest",
		"requestId": "amzn1.echo-api.request.0351aa00-4fc8-4338-a828-98b1a8dbea1c",
		"timestamp": "2018-04-27T04:40:08Z",
		"locale": "en-US",
		"intent": {
			"name": "RecipeIntent",
			"confirmationStatus": "NONE",
			"slots": {
				"item": {
					"name": "item",
					"value": "kindness",
					"resolutions": {
						"resolutionsPerAuthority": [
							{
								"authority": "amzn1.er-authority.echo-sdk.amzn1.ask.skill.aa3a79c1-f3ec-433c-a4a2-e41e6a325d5d.LIST_OF_ITEMS",
								"status": {
									"code": "ER_SUCCESS_MATCH"
								},
								"values": [
									{
										"value": {
											"name": "kindness",
											"id": "e9d6bfefbe0f6e457a00f031ad45d3c6"
										}
									}
								]
							}
						]
					},
					"confirmationStatus": "NONE"
				}
			}
		}
	}
}

{
	"body": {
		"version": "1.0",
		"response": {
			"outputSpeech": {
				"type": "PlainText",
				"text": "I'm sorry, I currently do not know that answer. What else can I help with?"
			},
			"reprompt": {
				"outputSpeech": {
					"type": "PlainText",
					"text": "What else can I help with?"
				}
			},
			"shouldEndSession": false
		},
		"sessionAttributes": {}
	}
}

Cloud Watch

04:40:08
2018-04-27T04:40:08.584Z 10535bad-49d5-11e8-a0fb-07f13268905c session applicationId: amzn1.ask.skill.aa3a79c1-f3ec-433c-a4a2-e41e6a325d5d 

04:40:08
2018-04-27T04:40:08.584Z 10535bad-49d5-11e8-a0fb-07f13268905c dispatch intent = RecipeIntent 
2018-04-27T04:40:08.584Z 10535bad-49d5-11e8-a0fb-07f13268905c dispatch intent = RecipeIntent

Please explain as if talking to an 11-year old, coding newbie here :-)

**Comment by franklin-lobb** [comment]
is this still an issue for you?

**Comment by AlexaforMuggles** [comment]
No thanks for asking. Here's the solution: 
Solution: the i in item was capitalised but needed to be in lower case
"RecipeIntent": function (intent, session, response) {
        var itemSlot = intent.slots.**i**tem
