### ISSUE TITLE
Initial usage is being answered with default welcome message

### ISSUE THREAD

**Issue by jtolksdo** [alexa/skill-sample-nodejs-howto#5]
Hi,
when I invoke the service the first time, I'm being prompted with the welcome message instead of an answer to my question. I've published the service, but it got rejected by Amazon, as initially the welcome message is being played.

**Comment by Rintel** [comment]
I'm having the same issue, don't know how I should solve it.

**Comment by dharalson** [comment]
Hi, 
Were you able to solve this problem?  I have the same thing where no matter what I use for utterance, the welcome message comes up.

**Comment by jtolksdo** [comment]
Hi, no, I have not been able to solve it. Hence, I've stopped looking into Alexa Skill development ...

**Comment by repath** [comment]
Even, I am so., with these templates, they just put over here for name sake and later on ,. just wondering how many requests are yet to be answered...

**Comment by franklin-lobb** [comment]
looks like this issue was resolved with a PR, but the issue was not closed.  @repath if you have a question, please feel free to open a new issue.
