### ISSUE TITLE
Update Node version to 12.x on alexa-skills-kit-nodejs-howtoskill

### ISSUE THREAD

**Issue by vinimoret** [alexa/skill-sample-nodejs-howto#60]
I'm having a problem every time I try to create a new lambda function from alexa-skills-kit-nodejs-howtoskill from serverless app repository I get the error below.
![image](https://user-images.githubusercontent.com/6878424/71948419-f2b81c00-319d-11ea-9b41-2102d88ed891.png)

**Comment by franklin-lobb** [comment]
Unfortunately, someone from the Alexa Education or SDK teams will need to update the application before it can be used.  Up for it @SleepyDeveloper? @YiddishNinja?

**Comment by Majita24** [comment]
I have the same mistake, someone could overcome

**Comment by vinimoret** [comment]
The template was updated to node version 10. not is workling
