### ISSUE TITLE
alexa.APP_ID does not work anymore

### ISSUE THREAD

**Issue by Jurik81** [alexa/skill-sample-nodejs-howto#7]
It is alexa.appId now.

**Comment by fibo** [comment]
I did a PR here https://github.com/alexa/skill-sample-nodejs-howto/pull/13 please merge to avoid mistakes for newbies like me.

Thanks to [GadgetChannel](https://forums.developer.amazon.com/users/78452/GadgetChannel.html) who ansered my forum question here:
https://forums.developer.amazon.com/questions/64797/warning-application-id-is-not-set.html

**Comment by krchandanvk** [comment]
not appid,
it should APP_ID

**Comment by franklin-lobb** [comment]
looks like this was resolved through a PR, but the issue was not closed at that time.  Closing...
